name: Pruebas Unitarias

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.0'
          extensions: mbstring, xml, intl

      - name: Instalar Composer dependencies
        run: composer install

      - name: Cambiar al directorio del proyecto
        run: cd D:\xampp\htdocs\sistemaPHP web

      - name: Instalar PHPUnit
        run: composer require --dev phpunit/phpunit

      - name: Agregar vendor/bin al PATH
        run: export PATH=$PATH:./vendor/bin

      - name: Ejecutar Pruebas Unitarias PHP
        run: ./vendor/bin/phpunit

      - name: Enviar notificación en caso de fallo
        if: failure()
        run: echo "Las pruebas unitarias han fallado. Revisa el flujo de trabajo."
